import { NextResponse } from "next/server";
import { mkdir, writeFile } from "fs/promises";
import path from "path";
import {
  PDFDocument,
  StandardFonts,
  rgb,
  degrees,
  type PDFFont,
  type PDFPage,
} from "pdf-lib";
import { prisma } from "@/lib/db";

function safeString(value: unknown) {
  if (typeof value !== "string") return "";
  return value.trim();
}

function cleanPdfText(value?: string | null) {
  return (value || "-")
    .replace(/₹/g, "Rs. ")
    .replace(/[“”]/g, '"')
    .replace(/[‘’]/g, "'")
    .replace(/\t/g, "  ");
}

function wrapText(text: string, font: PDFFont, fontSize: number, maxWidth: number) {
  const lines: string[] = [];

  for (const rawLine of text.split("\n")) {
    const words = rawLine.split(/\s+/).filter(Boolean);

    if (!words.length) {
      lines.push("");
      continue;
    }

    let line = "";

    for (const word of words) {
      const testLine = line ? `${line} ${word}` : word;
      const width = font.widthOfTextAtSize(testLine, fontSize);

      if (width <= maxWidth) {
        line = testLine;
      } else {
        if (line) lines.push(line);
        line = word;
      }
    }

    if (line) lines.push(line);
  }

  return lines;
}

async function getAgreement(agreementId: string) {
  return prisma.clientAgreement.findUnique({
    where: { id: agreementId },
    include: {
      project: {
        select: {
          id: true,
          title: true,
          projectType: true,
          location: true,
          plotSize: true,
          facing: true,
          floors: true,
          budget: true,
        },
      },
    },
  });
}

async function createAgreementPdf(
  agreement: NonNullable<Awaited<ReturnType<typeof getAgreement>>>,
) {
  const pdfDoc = await PDFDocument.create();

  const fontRegular = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const pageWidth = 595.28;
  const pageHeight = 841.89;
  const margin = 44;
  const contentWidth = pageWidth - margin * 2;

  let page: PDFPage = pdfDoc.addPage([pageWidth, pageHeight]);
  let y = pageHeight - margin;

  function addWatermark(currentPage: PDFPage) {
    currentPage.drawText("SIKHADENGE BUILD", {
      x: 110,
      y: 380,
      size: 44,
      font: fontBold,
      color: rgb(0.82, 0.76, 0.92),
      opacity: 0.16,
      rotate: degrees(35),
    });

    currentPage.drawText("Generated by Sikhadenge Build", {
      x: margin,
      y: 24,
      size: 8,
      font: fontRegular,
      color: rgb(0.45, 0.39, 0.55),
    });
  }

  function newPage() {
    addWatermark(page);
    page = pdfDoc.addPage([pageWidth, pageHeight]);
    y = pageHeight - margin;
  }

  function ensureSpace(height: number) {
    if (y - height < 58) {
      newPage();
    }
  }

  function drawTextLine(text: string, x: number, size: number, font: PDFFont, color = rgb(0.13, 0.08, 0.25)) {
    page.drawText(cleanPdfText(text), {
      x,
      y,
      size,
      font,
      color,
    });
  }

  function drawWrappedText(text: string, size = 9.5, font = fontRegular, lineHeight = 14) {
    const lines = wrapText(cleanPdfText(text), font, size, contentWidth);

    for (const line of lines) {
      ensureSpace(lineHeight);
      page.drawText(line || " ", {
        x: margin,
        y,
        size,
        font,
        color: rgb(0.25, 0.19, 0.36),
      });
      y -= lineHeight;
    }
  }

  function addSection(title: string, content?: string | null) {
    ensureSpace(45);
    y -= 8;

    page.drawText(title, {
      x: margin,
      y,
      size: 12,
      font: fontBold,
      color: rgb(0.13, 0.08, 0.25),
    });

    y -= 18;
    drawWrappedText(content || "-", 9.2, fontRegular, 13.4);
    y -= 6;
  }

  // Header
  page.drawText("Client Agreement", {
    x: margin,
    y,
    size: 24,
    font: fontBold,
    color: rgb(0.08, 0.04, 0.18),
  });

  page.drawText("Sikhadenge Build", {
    x: pageWidth - margin - 110,
    y: y + 4,
    size: 12,
    font: fontBold,
    color: rgb(0.49, 0.23, 0.93),
  });

  y -= 28;

  page.drawText(cleanPdfText(agreement.title), {
    x: margin,
    y,
    size: 12,
    font: fontBold,
    color: rgb(0.13, 0.08, 0.25),
  });

  y -= 18;

  const metaLines = [
    `Project: ${agreement.project?.title || "-"}`,
    `Type: ${agreement.project?.projectType || "-"}`,
    `Location: ${agreement.project?.location || "-"}`,
    `Plot: ${agreement.project?.plotSize || "-"}`,
    `Facing: ${agreement.project?.facing || "-"}`,
    `Floors: ${agreement.project?.floors || "-"}`,
    `Budget: ${agreement.project?.budget || "-"}`,
    `Status: ${agreement.status}`,
  ];

  for (const meta of metaLines) {
    ensureSpace(14);
    drawTextLine(meta, margin, 9, fontRegular, rgb(0.36, 0.31, 0.47));
    y -= 13;
  }

  y -= 8;

  addSection("Scope, Party Details and Project Details", agreement.scope);
  addSection("Deliverables", agreement.deliverables);
  addSection("Commercials and Payment Terms", agreement.paymentTerms);
  addSection("Timeline, Revision and Client Responsibility", agreement.revisionTerms);
  addSection("Terms, Conditions and Disclaimer", agreement.disclaimer);

  ensureSpace(85);
  y -= 10;

  page.drawText("Acceptance / Signatures", {
    x: margin,
    y,
    size: 12,
    font: fontBold,
    color: rgb(0.13, 0.08, 0.25),
  });

  y -= 52;

  page.drawLine({
    start: { x: margin, y },
    end: { x: margin + 200, y },
    thickness: 1,
    color: rgb(0.78, 0.72, 0.85),
  });

  page.drawLine({
    start: { x: pageWidth - margin - 200, y },
    end: { x: pageWidth - margin, y },
    thickness: 1,
    color: rgb(0.78, 0.72, 0.85),
  });

  y -= 14;

  page.drawText("Service Provider Signature", {
    x: margin,
    y,
    size: 9,
    font: fontRegular,
    color: rgb(0.36, 0.31, 0.47),
  });

  page.drawText("Client Signature", {
    x: pageWidth - margin - 200,
    y,
    size: 9,
    font: fontRegular,
    color: rgb(0.36, 0.31, 0.47),
  });

  addWatermark(page);

  const pages = pdfDoc.getPages();
  pages.forEach((pdfPage, index) => {
    pdfPage.drawText(`Page ${index + 1} of ${pages.length}`, {
      x: pageWidth / 2 - 25,
      y: 24,
      size: 8,
      font: fontRegular,
      color: rgb(0.45, 0.39, 0.55),
    });
  });

  return Buffer.from(await pdfDoc.save());
}

export async function POST(request: Request) {
  try {
    const body = await request.json().catch(() => null);

    if (!body || typeof body !== "object") {
      return NextResponse.json(
        { ok: false, error: "Invalid JSON body" },
        { status: 400 },
      );
    }

    const agreementId = safeString(body.agreementId);

    if (!agreementId) {
      return NextResponse.json(
        { ok: false, error: "agreementId is required" },
        { status: 400 },
      );
    }

    const agreement = await getAgreement(agreementId);

    if (!agreement) {
      return NextResponse.json(
        { ok: false, error: "Agreement not found" },
        { status: 404 },
      );
    }

    const outputDir = path.join(process.cwd(), "public", "generated", "agreements");
    await mkdir(outputDir, { recursive: true });

    const fileName = `${agreement.id}.pdf`;
    const filePath = path.join(outputDir, fileName);
    const pdfBuffer = await createAgreementPdf(agreement);

    await writeFile(filePath, pdfBuffer);

    const pdfUrl = `/generated/agreements/${fileName}`;
    const downloadUrl = `/api/agreements/download-pdf?agreementId=${agreement.id}`;

    return NextResponse.json({
      ok: true,
      pdfUrl,
      downloadUrl,
      fileName,
      agreementId: agreement.id,
    });
  } catch (error) {
    console.error("AGREEMENT_PDF_EXPORT_ERROR", error);

    const message = error instanceof Error ? error.message : "Failed to export agreement PDF";

    return NextResponse.json(
      { ok: false, error: message },
      { status: 500 },
    );
  }
}
