import { NextResponse } from "next/server";
import PDFDocument from "pdfkit";
import { mkdir, writeFile } from "fs/promises";
import path from "path";
import { prisma } from "@/lib/db";

function safeString(value: unknown) {
  if (typeof value !== "string") return "";
  return value.trim();
}

function cleanPdfText(value?: string | null) {
  return (value || "—")
    .replace(/₹/g, "Rs. ")
    .replace(/[“”]/g, '"')
    .replace(/[‘’]/g, "'")
    .replace(/\t/g, "  ");
}

function addSection(doc: PDFKit.PDFDocument, title: string, content?: string | null) {
  doc.moveDown(0.8);
  doc
    .font("Helvetica-Bold")
    .fontSize(12)
    .fillColor("#21133f")
    .text(title, { underline: false });

  doc.moveDown(0.3);
  doc
    .font("Helvetica")
    .fontSize(9.5)
    .fillColor("#3f315d")
    .text(cleanPdfText(content), {
      align: "left",
      lineGap: 3,
    });
}

function createPdfBuffer(agreement: Awaited<ReturnType<typeof getAgreement>>) {
  if (!agreement) {
    throw new Error("Agreement not found");
  }

  return new Promise<Buffer>((resolve, reject) => {
    const chunks: Buffer[] = [];
    const doc = new PDFDocument({
      size: "A4",
      margin: 42,
      info: {
        Title: agreement.title,
        Author: "Sikhadenge Build",
        Subject: "Client Agreement",
      },
    });

    doc.on("data", (chunk) => chunks.push(Buffer.from(chunk)));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc
      .font("Helvetica-Bold")
      .fontSize(20)
      .fillColor("#140b2d")
      .text("Client Agreement", { align: "center" });

    doc.moveDown(0.35);

    doc
      .font("Helvetica")
      .fontSize(9)
      .fillColor("#817397")
      .text("Generated by Sikhadenge Build", { align: "center" });

    doc.moveDown(1);

    doc
      .roundedRect(42, doc.y, 511, 82, 12)
      .fillAndStroke("#fbf8ff", "#ded5ec");

    const boxY = doc.y + 14;

    doc
      .font("Helvetica-Bold")
      .fontSize(13)
      .fillColor("#21133f")
      .text(cleanPdfText(agreement.title), 58, boxY, { width: 480 });

    doc
      .font("Helvetica")
      .fontSize(9)
      .fillColor("#5d5077")
      .text(`Project: ${cleanPdfText(agreement.project?.title)}`, 58, boxY + 24, { width: 235 })
      .text(`Type: ${cleanPdfText(agreement.project?.projectType)}`, 300, boxY + 24, { width: 235 })
      .text(`Location: ${cleanPdfText(agreement.project?.location)}`, 58, boxY + 42, { width: 235 })
      .text(`Status: ${cleanPdfText(agreement.status)}`, 300, boxY + 42, { width: 235 });

    doc.y = boxY + 78;

    addSection(doc, "Scope, Party Details and Project Details", agreement.scope);
    addSection(doc, "Deliverables", agreement.deliverables);
    addSection(doc, "Commercials and Payment Terms", agreement.paymentTerms);
    addSection(doc, "Timeline, Revision and Client Responsibility", agreement.revisionTerms);
    addSection(doc, "Terms, Conditions and Disclaimer", agreement.disclaimer);

    doc.moveDown(1.2);

    doc
      .font("Helvetica-Bold")
      .fontSize(10)
      .fillColor("#21133f")
      .text("Acceptance / Signatures");

    doc.moveDown(0.8);

    const signY = doc.y;
    doc
      .font("Helvetica")
      .fontSize(9)
      .fillColor("#3f315d")
      .text("Service Provider Signature", 42, signY + 42, { width: 220 })
      .text("Client Signature", 330, signY + 42, { width: 220 });

    doc
      .moveTo(42, signY + 35)
      .lineTo(250, signY + 35)
      .strokeColor("#ded5ec")
      .stroke();

    doc
      .moveTo(330, signY + 35)
      .lineTo(553, signY + 35)
      .strokeColor("#ded5ec")
      .stroke();

    const pages = doc.bufferedPageRange();
    for (let i = 0; i < pages.count; i++) {
      doc.switchToPage(i);
      doc
        .font("Helvetica")
        .fontSize(8)
        .fillColor("#817397")
        .text(
          `Sikhadenge Build | Page ${i + 1} of ${pages.count}`,
          42,
          812,
          { width: 511, align: "center" },
        );
    }

    doc.end();
  });
}

async function getAgreement(agreementId: string) {
  return prisma.clientAgreement.findUnique({
    where: { id: agreementId },
    include: {
      project: {
        select: {
          id: true,
          title: true,
          projectType: true,
          location: true,
          plotSize: true,
          facing: true,
          floors: true,
          budget: true,
        },
      },
    },
  });
}

export async function POST(request: Request) {
  try {
    const body = await request.json().catch(() => null);

    if (!body || typeof body !== "object") {
      return NextResponse.json(
        { ok: false, error: "Invalid JSON body" },
        { status: 400 },
      );
    }

    const agreementId = safeString(body.agreementId);

    if (!agreementId) {
      return NextResponse.json(
        { ok: false, error: "agreementId is required" },
        { status: 400 },
      );
    }

    const agreement = await getAgreement(agreementId);

    if (!agreement) {
      return NextResponse.json(
        { ok: false, error: "Agreement not found" },
        { status: 404 },
      );
    }

    const outputDir = path.join(process.cwd(), "public", "generated", "agreements");
    await mkdir(outputDir, { recursive: true });

    const fileName = `${agreement.id}.pdf`;
    const filePath = path.join(outputDir, fileName);
    const pdfBuffer = await createPdfBuffer(agreement);

    await writeFile(filePath, pdfBuffer);

    const pdfUrl = `/generated/agreements/${fileName}`;

    return NextResponse.json({
      ok: true,
      pdfUrl,
      fileName,
      agreementId: agreement.id,
    });
  } catch (error) {
    console.error("AGREEMENT_PDF_EXPORT_ERROR", error);

    const message = error instanceof Error ? error.message : "Failed to export agreement PDF";

    return NextResponse.json(
      { ok: false, error: message },
      { status: 500 },
    );
  }
}
